-- lab.db (Postgres dialect): domain data for the Lab Equipment Booking assistant.
CREATE TABLE IF NOT EXISTS student (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_no             TEXT NOT NULL UNIQUE,
    name                TEXT NOT NULL,
    dept                TEXT NOT NULL,
    max_active_bookings INTEGER NOT NULL DEFAULT 2 CHECK (max_active_bookings >= 0)
);

CREATE TABLE IF NOT EXISTS equipment (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              TEXT NOT NULL,
    category          TEXT NOT NULL,
    requires_training TEXT,
    version           INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0)
);

CREATE TABLE IF NOT EXISTS training (
    student_id BIGINT NOT NULL REFERENCES student (id),
    course     TEXT NOT NULL,
    completed  INTEGER NOT NULL DEFAULT 0 CHECK (completed IN (0, 1)),
    PRIMARY KEY (student_id, course)
);

-- Business rules live in data, not only in prompts.
CREATE TABLE IF NOT EXISTS policy (
    name  TEXT PRIMARY KEY,
    value INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS booking (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   BIGINT NOT NULL REFERENCES student (id),
    equipment_id BIGINT NOT NULL REFERENCES equipment (id),
    slot         TEXT NOT NULL,
    returned     INTEGER NOT NULL DEFAULT 0 CHECK (returned IN (0, 1)),
    created_at   DOUBLE PRECISION NOT NULL,
    UNIQUE (equipment_id, slot),
    UNIQUE (student_id, equipment_id, slot)
);

CREATE TABLE IF NOT EXISTS notification (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_no    TEXT NOT NULL,
    message    TEXT NOT NULL,
    dedupe_key TEXT NOT NULL UNIQUE,
    created_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS idempotency (
    key        TEXT PRIMARY KEY,
    tool_name  TEXT NOT NULL,
    result     TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL
);